modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "hexprojectiles"
version = "${version}"
displayName = "Hex Projectiles"
authors = "PecantPie"
description = '''
A minecraft mod that adds integration between Hex Casting and Create: Big Cannons.
'''
logoFile = "icon.png"

[[dependencies.hexprojectiles]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexprojectiles]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexprojectiles]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"

[[dependencies.hexprojectiles]]
modId="createbigcannons"
mandatory=true
versionRange="${cbc_version}"
ordering="NONE"
side="BOTH"